import { expect, test } from '@playwright/test';

test('图表标注自动保存到笔记、分组并重新打开修改', async ({page}) => {
  // HTTP access via LAN/Tailscale does not expose crypto.randomUUID.
  await page.addInitScript(() => Object.defineProperty(window.crypto, 'randomUUID', {value:undefined, configurable:true}));
  let saved:any;
  let group:any;
  await page.route('**/api/**',async route=>{
    const path=new URL(route.request().url()).pathname;
    const method=route.request().method();
    let json:any=[];
    if(path==='/api/notes/groups') {
      if(method==='POST') group={id:'g1',name:route.request().postDataJSON().name};
      json=method==='POST'?group:group?[group]:[];
    } else if(path==='/api/notes') {
      if(method==='POST') {saved={id:'n1',revision:1,updated_at:'2026-09-19T00:00:00',group_id:null,...route.request().postDataJSON()};json=saved;}
      else json=saved?[{...saved,has_chart:!!saved.chart}]:[];
    } else if(path==='/api/notes/n1') {
      if(method==='PUT') saved={...route.request().postDataJSON(),revision:saved.revision+1};
      json=saved;
    } else if(path.endsWith('/bars')) json=Array.from({length:160},(_,i)=>({symbol:'600519.SH',timestamp:new Date(Date.UTC(2026,0,i+1)).toISOString(),open:10+i/10,close:10.1+i/10,low:9.8+i/10,high:10.5+i/10,volume_shares:10000,amount_cny:100000}));
    else if(path.endsWith('/overview')) json={symbol:'600519.SH',name:'贵州茅台',quote:null};
    await route.fulfill({json});
  });
  await page.goto('/');
  await page.getByRole('button',{name:'笔记',exact:true}).click();
  await page.getByText('管理笔记分组').click();
  await page.getByLabel('新笔记分组名称').fill('突破复盘');
  await page.getByRole('button',{name:'创建笔记分组'}).click();
  await page.getByRole('button',{name:'K 线研究',exact:true}).click();
  await expect(page.getByRole('img',{name:'K 线与成交量图'})).toBeVisible();
  await page.getByRole('button',{name:'标注并记笔记'}).hover();
  await expect(page.getByRole('tooltip')).toContainText('在当前K线图上添加标注，自动保存到笔记');
  await page.getByRole('button',{name:'该股票的图表笔记'}).hover();
  await expect(page.getByRole('tooltip')).toContainText('查看和编辑这只股票已保存的图表笔记');
  await page.getByRole('button',{name:'标注并记笔记'}).click();
  await expect(page.getByAltText('笔记中的K线快照')).toBeVisible();
  await page.getByLabel('笔记标题').fill('突破复盘测试');
  await page.getByLabel('笔记分组',{exact:true}).selectOption('g1');
  await page.getByRole('button',{name:'文字',exact:true}).click();
  const canvas=page.getByLabel('K线笔记标注画布');
  await canvas.click({position:{x:160,y:120}});
  await page.getByLabel('编辑图中文字').fill('突破观察');
  await page.getByLabel('编辑图中文字').press('Enter');
  await page.getByRole('button',{name:'箭头',exact:true}).click();
  const bounds=(await canvas.boundingBox())!;
  await page.mouse.move(bounds.x+200,bounds.y+150);
  await page.mouse.down();
  await page.mouse.move(bounds.x+300,bounds.y+200,{steps:8});
  await page.mouse.up();
  await page.getByLabel('文字大小').fill('28');
  await page.getByRole('button',{name:'选择移动',exact:true}).click();
  const arrow=canvas.locator('[data-annotation-id]').nth(1);
  const before=await arrow.getAttribute('data-x');
  await page.mouse.move(bounds.x+250,bounds.y+175);
  await page.mouse.down();
  await page.mouse.move(bounds.x+290,bounds.y+195,{steps:5});
  await page.mouse.up();
  await expect(arrow).not.toHaveAttribute('data-x',before!);
  await page.getByRole('button',{name:'撤销',exact:true}).click();
  await expect(arrow).toHaveAttribute('data-x',before!);
  await page.getByRole('button',{name:'重做',exact:true}).click();
  const text=canvas.locator('[data-annotation-id]').first();
  const textBox=(await text.locator('text').boundingBox())!;
  const oldTextX=await text.getAttribute('data-x');
  await page.mouse.move(textBox.x+10,textBox.y+5);
  await page.mouse.down();
  await page.mouse.move(textBox.x+60,textBox.y+20,{steps:5});
  await page.mouse.up();
  await expect(text).not.toHaveAttribute('data-x',oldTextX!);
  await page.getByLabel('文字大小').fill('32');
  await expect(text.locator('text')).toHaveAttribute('font-size','32');
  await text.locator('text').dblclick();
  await page.getByLabel('编辑图中文字').fill('拖动后的文字');
  await page.getByLabel('编辑图中文字').press('Enter');
  await expect(text.locator('text')).toHaveText('拖动后的文字');
  await page.getByRole('button',{name:'框选',exact:true}).click();
  const currentBounds=(await canvas.boundingBox())!;
  await page.mouse.move(currentBounds.x+400,currentBounds.y+200);
  await page.mouse.down();
  await page.mouse.move(currentBounds.x+500,currentBounds.y+300,{steps:5});
  await page.mouse.up();
  const box=canvas.locator('[data-annotation-id]').nth(2);
  const oldWidth=await box.locator('rect').getAttribute('width');
  const handle=(await box.locator('[data-handle="end"]').boundingBox())!;
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);
  await page.mouse.down();
  await page.mouse.move(handle.x+50,handle.y+40,{steps:5});
  await page.mouse.up();
  await expect(box.locator('rect')).not.toHaveAttribute('width',oldWidth!);

  await page.getByLabel('笔记正文').fill('等待下一根确认');
  await expect(page.getByRole('status')).toHaveText('已保存');
  expect(saved.annotations).toHaveLength(3);
  expect(saved.annotations[0].fontSize).toBe(32);
  expect(saved.chart.image).toMatch(/^data:image\/png;base64,/);
  await page.getByRole('button',{name:'保存并关闭'}).click();
  await page.getByRole('button',{name:'笔记',exact:true}).click();
  await page.getByRole('button',{name:'打开笔记'}).click();
  await expect(page.getByLabel('笔记正文')).toHaveValue('等待下一根确认');
  await expect(canvas.locator('[data-annotation-id]').first().locator('text')).toHaveText('拖动后的文字');
  await canvas.locator('[data-annotation-id]').first().locator('text').dblclick();
  await page.getByLabel('编辑图中文字').fill('已确认突破');
  await page.getByLabel('编辑图中文字').press('Enter');
  await page.getByRole('button',{name:'保存并关闭'}).click();
  await page.getByRole('button',{name:'K 线研究',exact:true}).click();
  await page.getByRole('button',{name:'该股票的图表笔记'}).click();
  await page.getByLabel('打开该股票笔记').selectOption('n1');
  await expect(canvas.locator('[data-annotation-id]').first().locator('text')).toHaveText('已确认突破');
  await expect(page.getByText('重新定位',{exact:true})).toHaveCount(0);
  await page.screenshot({path:'/tmp/astock-notes-preview.png',fullPage:true});
});
